//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace ALF.SL.UploadWeb.SilverlightUploadServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SilverlightUploadServiceReference.SilverlightUploadServiceSoap")]
    public interface SilverlightUploadServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/StoreFileAdvanced", ReplyAction="*")]
        System.IAsyncResult BeginStoreFileAdvanced(ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequest request, System.AsyncCallback callback, object asyncState);
        
        ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponse EndStoreFileAdvanced(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CancelUpload", ReplyAction="*")]
        System.IAsyncResult BeginCancelUpload(ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequest request, System.AsyncCallback callback, object asyncState);
        
        ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponse EndCancelUpload(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreFileAdvancedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreFileAdvanced", Namespace="http://tempuri.org/", Order=0)]
        public ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequestBody Body;
        
        public StoreFileAdvancedRequest() {
        }
        
        public StoreFileAdvancedRequest(ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StoreFileAdvancedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] data;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int dataLength;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string parameters;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool firstChunk;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool lastChunk;
        
        public StoreFileAdvancedRequestBody() {
        }
        
        public StoreFileAdvancedRequestBody(string fileName, byte[] data, int dataLength, string parameters, bool firstChunk, bool lastChunk) {
            this.fileName = fileName;
            this.data = data;
            this.dataLength = dataLength;
            this.parameters = parameters;
            this.firstChunk = firstChunk;
            this.lastChunk = lastChunk;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoreFileAdvancedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoreFileAdvancedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponseBody Body;
        
        public StoreFileAdvancedResponse() {
        }
        
        public StoreFileAdvancedResponse(ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StoreFileAdvancedResponseBody {
        
        public StoreFileAdvancedResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelUploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelUpload", Namespace="http://tempuri.org/", Order=0)]
        public ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequestBody Body;
        
        public CancelUploadRequest() {
        }
        
        public CancelUploadRequest(ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelUploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public CancelUploadRequestBody() {
        }
        
        public CancelUploadRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelUploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelUploadResponse", Namespace="http://tempuri.org/", Order=0)]
        public ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponseBody Body;
        
        public CancelUploadResponse() {
        }
        
        public CancelUploadResponse(ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CancelUploadResponseBody {
        
        public CancelUploadResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SilverlightUploadServiceSoapChannel : ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SilverlightUploadServiceSoapClient : System.ServiceModel.ClientBase<ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap>, ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap {
        
        private BeginOperationDelegate onBeginStoreFileAdvancedDelegate;
        
        private EndOperationDelegate onEndStoreFileAdvancedDelegate;
        
        private System.Threading.SendOrPostCallback onStoreFileAdvancedCompletedDelegate;
        
        private BeginOperationDelegate onBeginCancelUploadDelegate;
        
        private EndOperationDelegate onEndCancelUploadDelegate;
        
        private System.Threading.SendOrPostCallback onCancelUploadCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SilverlightUploadServiceSoapClient() {
        }
        
        public SilverlightUploadServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SilverlightUploadServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SilverlightUploadServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SilverlightUploadServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> StoreFileAdvancedCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CancelUploadCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap.BeginStoreFileAdvanced(ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginStoreFileAdvanced(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginStoreFileAdvanced(string fileName, byte[] data, int dataLength, string parameters, bool firstChunk, bool lastChunk, System.AsyncCallback callback, object asyncState) {
            ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequest inValue = new ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequest();
            inValue.Body = new ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.data = data;
            inValue.Body.dataLength = dataLength;
            inValue.Body.parameters = parameters;
            inValue.Body.firstChunk = firstChunk;
            inValue.Body.lastChunk = lastChunk;
            return ((ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap)(this)).BeginStoreFileAdvanced(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponse ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap.EndStoreFileAdvanced(System.IAsyncResult result) {
            return base.Channel.EndStoreFileAdvanced(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndStoreFileAdvanced(System.IAsyncResult result) {
            ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponse retVal = ((ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap)(this)).EndStoreFileAdvanced(result);
        }
        
        private System.IAsyncResult OnBeginStoreFileAdvanced(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileName = ((string)(inValues[0]));
            byte[] data = ((byte[])(inValues[1]));
            int dataLength = ((int)(inValues[2]));
            string parameters = ((string)(inValues[3]));
            bool firstChunk = ((bool)(inValues[4]));
            bool lastChunk = ((bool)(inValues[5]));
            return this.BeginStoreFileAdvanced(fileName, data, dataLength, parameters, firstChunk, lastChunk, callback, asyncState);
        }
        
        private object[] OnEndStoreFileAdvanced(System.IAsyncResult result) {
            this.EndStoreFileAdvanced(result);
            return null;
        }
        
        private void OnStoreFileAdvancedCompleted(object state) {
            if ((this.StoreFileAdvancedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.StoreFileAdvancedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void StoreFileAdvancedAsync(string fileName, byte[] data, int dataLength, string parameters, bool firstChunk, bool lastChunk) {
            this.StoreFileAdvancedAsync(fileName, data, dataLength, parameters, firstChunk, lastChunk, null);
        }
        
        public void StoreFileAdvancedAsync(string fileName, byte[] data, int dataLength, string parameters, bool firstChunk, bool lastChunk, object userState) {
            if ((this.onBeginStoreFileAdvancedDelegate == null)) {
                this.onBeginStoreFileAdvancedDelegate = new BeginOperationDelegate(this.OnBeginStoreFileAdvanced);
            }
            if ((this.onEndStoreFileAdvancedDelegate == null)) {
                this.onEndStoreFileAdvancedDelegate = new EndOperationDelegate(this.OnEndStoreFileAdvanced);
            }
            if ((this.onStoreFileAdvancedCompletedDelegate == null)) {
                this.onStoreFileAdvancedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnStoreFileAdvancedCompleted);
            }
            base.InvokeAsync(this.onBeginStoreFileAdvancedDelegate, new object[] {
                        fileName,
                        data,
                        dataLength,
                        parameters,
                        firstChunk,
                        lastChunk}, this.onEndStoreFileAdvancedDelegate, this.onStoreFileAdvancedCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap.BeginCancelUpload(ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCancelUpload(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCancelUpload(string fileName, System.AsyncCallback callback, object asyncState) {
            ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequest inValue = new ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequest();
            inValue.Body = new ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequestBody();
            inValue.Body.fileName = fileName;
            return ((ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap)(this)).BeginCancelUpload(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponse ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap.EndCancelUpload(System.IAsyncResult result) {
            return base.Channel.EndCancelUpload(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndCancelUpload(System.IAsyncResult result) {
            ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponse retVal = ((ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap)(this)).EndCancelUpload(result);
        }
        
        private System.IAsyncResult OnBeginCancelUpload(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string fileName = ((string)(inValues[0]));
            return this.BeginCancelUpload(fileName, callback, asyncState);
        }
        
        private object[] OnEndCancelUpload(System.IAsyncResult result) {
            this.EndCancelUpload(result);
            return null;
        }
        
        private void OnCancelUploadCompleted(object state) {
            if ((this.CancelUploadCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CancelUploadCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CancelUploadAsync(string fileName) {
            this.CancelUploadAsync(fileName, null);
        }
        
        public void CancelUploadAsync(string fileName, object userState) {
            if ((this.onBeginCancelUploadDelegate == null)) {
                this.onBeginCancelUploadDelegate = new BeginOperationDelegate(this.OnBeginCancelUpload);
            }
            if ((this.onEndCancelUploadDelegate == null)) {
                this.onEndCancelUploadDelegate = new EndOperationDelegate(this.OnEndCancelUpload);
            }
            if ((this.onCancelUploadCompletedDelegate == null)) {
                this.onCancelUploadCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCancelUploadCompleted);
            }
            base.InvokeAsync(this.onBeginCancelUploadDelegate, new object[] {
                        fileName}, this.onEndCancelUploadDelegate, this.onCancelUploadCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap CreateChannel() {
            return new SilverlightUploadServiceSoapClientChannel(this);
        }
        
        private class SilverlightUploadServiceSoapClientChannel : ChannelBase<ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap>, ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap {
            
            public SilverlightUploadServiceSoapClientChannel(System.ServiceModel.ClientBase<ALF.SL.UploadWeb.SilverlightUploadServiceReference.SilverlightUploadServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginStoreFileAdvanced(ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("StoreFileAdvanced", _args, callback, asyncState);
                return _result;
            }
            
            public ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponse EndStoreFileAdvanced(System.IAsyncResult result) {
                object[] _args = new object[0];
                ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponse _result = ((ALF.SL.UploadWeb.SilverlightUploadServiceReference.StoreFileAdvancedResponse)(base.EndInvoke("StoreFileAdvanced", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCancelUpload(ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CancelUpload", _args, callback, asyncState);
                return _result;
            }
            
            public ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponse EndCancelUpload(System.IAsyncResult result) {
                object[] _args = new object[0];
                ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponse _result = ((ALF.SL.UploadWeb.SilverlightUploadServiceReference.CancelUploadResponse)(base.EndInvoke("CancelUpload", _args, result)));
                return _result;
            }
        }
    }
}
